INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_MASCON_DECODER_MODULE mascon_decoder_module)

FIND_PATH(
    MASCON_DECODER_MODULE_INCLUDE_DIRS
    NAMES mascon_decoder_module/api.h
    HINTS $ENV{MASCON_DECODER_MODULE_DIR}/include
        ${PC_MASCON_DECODER_MODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    MASCON_DECODER_MODULE_LIBRARIES
    NAMES gnuradio-mascon_decoder_module
    HINTS $ENV{MASCON_DECODER_MODULE_DIR}/lib
        ${PC_MASCON_DECODER_MODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MASCON_DECODER_MODULE DEFAULT_MSG MASCON_DECODER_MODULE_LIBRARIES MASCON_DECODER_MODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(MASCON_DECODER_MODULE_LIBRARIES MASCON_DECODER_MODULE_INCLUDE_DIRS)

